# Autogenerated wrapper script for ports_of_call_jll for aarch64-linux-gnu
JLLWrappers.@generate_wrapper_header("ports_of_call")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
